
from enum import Enum

class RoleEnum(str,Enum):
  admin = "Admin"
  user = "User"

from enum import Enum

class AvocateCategoryEnum(str, Enum):
  ARTISAN_COMMECA = "Artisan-commerçant"
  COMMERCANT = "Commerçant"
  ARTISAN = "Artisan"
  OFFICIER_PUBLIC = "Officier public ou ministériel"
  PROFESSION_LIBERALE = "Profession libérale"
  EXPLOITANT_AGRICOLE = "Exploitant agricole"
  AGENT_COMMERCIAL = "Agent commercial"
  ASSOCIE_GERANT_DE_SOCIETE = "Associé Gérant de société"
  AUTRE_PERSONNE_PHYSIQUE = "(Autre) personne physique"
  INDIVISION = "Indivision"
  SOCIETE_CREE_DE_FAIT = "Société créée de fait"
  SOCIETE_EN_PARTICIPATION = "Société en participation"
  FIDUCIE = "Fiducie"
  PAROISSE_HORS_ZONE_CONCORDATAIRE = "Paroisse hors zone concordataire"
  AUTRE_GROUPEMENT_DE_DROIT_PRIVE_NON_DOTE_DE_LA_PERSONNALITE_MORALE = "Autre groupement de droit privé non doté de la personnalité morale"
  PERSONNE_MORALE_DE_DROIT_ETRANGEIM_IMMATRICULEE_AU_RCS = "Personne morale de droit étranger immatriculée au RCS (registre du commerce et des sociétés)"
  PERSONNE_MORALE_DE_DROIT_ETRANGEIM_NON_IMMATRICULEE_AU_RCS = "Personne morale de droit étranger non immatriculée au RCS"
  ESTABLISSEMENT_PUBLIC_OU_REGIE_A_CARACTERE_INDUSTRIEL_OU_COMMERCIAL = "Établissement public ou régie à caractère industriel ou commercial"
  SOCIETE_COOPERATIVE_COMMERCIALE_PARTICULIERE = "Société coopérative commerciale particulière"
  SOCIETE_EN_NOM_COLLECTIF = "Société en nom collectif"
  SOCIETE_EN_COMMANDETI = "Société en commandite"
  SOCIETE_A_RESPONSABILITE_LIMITEE_SARL = "Société à responsabilité limitée (SARL)"
  SOCIETE_ANONYME_A_CONSEIL_DA_ADMINISTRATION = "Société anonyme à conseil d'administration"
  SOCIETE_ANONYME_A_DIRECTOIRE = "Société anonyme à directoire"
  SOCIETE_ANONYME_PAR_ACTIONS_SIMPLIFIEES = "Société anonyme par actions simplifiées"
  SOCIETE_EUROPEENNE = "Société européenne"
  CAISSE_DEPARGNEMENT_ET_DE_PREVOYANCE = "Caisse d'épargne et de prévoyance"
  GROUPEMENT_DINTERET_ECONOMIQUE = "Groupement d'intérêt économique"
  SOCIETE_COOPERATIVE_AGRICOLE = "Société coopérative agricole"
  SOCIETE_NON_COMMERCIALE_D_ASSURANCES = "Société non commerciale d'assurances"
  SOCIETE_CIVILE = "Société civile"
  AUTRES_PERSONNES_DE_DROIT_PRIVE_INSCRITES_AU_REGISTRE_DU_COMMERCE_ET_DES_SOCIETES = "Autres personnes de droit privé inscrites au registre du commerce et des sociétés"
  ADMINISTRATION_DE_LETAT = "Administration de l'état"
  COLLECTIVITE_TERRITORIALE = "Collectivité territoriale"
  ESTABLISSEMENT_PUBLIC_ADMINISTRATIF = "Établissement public administratif"
  AUTRE_PERSONNE_MORALE_DE_DROIT_PUBLIC_ADMINISTRATIF = "Autre personne morale de droit public administratif"
  ORGANISME_GERANT_UN_REGIME_DE_PROTECTION_SOCIALE_A_ADHESION_OBLIGATOIRE = "Organisme gérant un régime de protection sociale à adhésion obligatoire"
  ORGANISME_MUTUALISTE = "Organisme mutualiste"
  COMITE_DENTREPRISE = "Comité d'entreprise"
  ORGANISME_PROFESSIONNEL = "Organisme professionnel"
  SYNDICAT_DE_PROPRIETAIRES = "Syndicat de propriétaires"
  ASSOCIATION_LOI_1901_OU_ASSIMILEE = "Association loi 1901 ou assimilé"
  FOUNDATION = "Fondation"

class AlgerianWilayas(str, Enum):
   ADJERA = "Adjera"
   AIN_DEFLA = "Ain Defla"
   AIN_TEMOUCHENT = "Ain Temouchent"
   AOUDA = "Aouda"
   BATNA = "Batna"
   BEJAIA = "Bejaia"
   BISKRA = "Biskra"
   BLIDA = "Blida"
   BOUMERDES = "Boumerdes"
   CHLEF = "Chlef"
   CONSTANTINE = "Constantine"
   DJELFA = "Djelifa"
   EL_OUDJA = "El Oued"
   EL_TAFIOUINE = "El Taref"
   GUELMA = "Guelma"
   ILLIZI = "Illizi"
   JIJEL = "Jijel"
   KHELLILI = "Khemis Miliana"
   MASCARA = "Mascara"
   MOUILLET = "Mouila"
   MOSTAGANEM = "Mostaganem"
   MSILA = "M'Sila"
   NAAMOUNA = "Naama"
   ORAN = "Oran"
   OUARGLA = "Ouargla"
   RELIZANE = "Relizane"
   SAIDA = "Saida"
   SETIF = "Setif"
   SKIKDA = "Skikda"
   SOUK_AIUN = "Souk Ahras"
   TEBESSA = "Tebessa"
   TELEMCEN = "Tlemcen"
   TIARET = "Tiaret"
   TIPAZA = "Tipaza"
   TISSEMSILT = "Tissemsilt"
   TIZI_OUZOU = "Tizi Ouzou"
   TLEMCEN = "Tlemcen"